version: '3'
services:
  backend:
    container_name: backend
    image: okqkrwhdtjd/backend:${DOCKER_IMAGE_TAG}
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    ports:
      - "80:80"
    image: okqkrwhdtjd/frontend:${DOCKER_IMAGE_TAG}


