name: devops test

on:
  push:
    branches: [ master ]
    
jobs:
  deploy:
    name: Deploy to k8s
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew docker -Pplatform=backend
          
              - name: Build with Gradle
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: okqkrwhdtjd1234
          password: Okqkrwhdtjd1234
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: okqkrwhdtjd1234/backend:1.0
